spring:
  profiles:
    active:
    - local
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
      media-types:
        xls: application/vnd.ms-excel

---
spring:
  profiles: local
  jpa:
    hibernate.ddl-auto: validate # create, create-drop, update, validate
    show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmeventdb?useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password:
# Hikari DataSource
    hikari:
      maximumPoolSize: 100
      minimumIdle: 5
      connectionTestQuery: select 1
      connectionTimeout: 3000 # 1"
      idleTimeout: 10000  # at least 10" over
